In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
le = LabelEncoder()

In [3]:
crx = pd.read_csv(r"C:\Users\s5030\Desktop\研究所\機器學習\hw1\crx.csv")
data = pd.read_csv(r"C:\Users\s5030\Desktop\研究所\機器學習\hw1\data.csv")

In [4]:
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15,label
0,b,30.83,0.000,u,g,w,v,1.25,t,t,1,f,g,202,0,+
1,a,58.67,4.460,u,g,q,h,3.04,t,t,6,f,g,43,560,+
2,a,24.5,0.500,u,g,q,h,1.50,t,f,0,f,g,280,824,+
3,b,27.83,1.540,u,g,w,v,3.75,t,t,5,t,g,100,3,+
4,b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,b,21.08,10.085,y,p,e,h,1.25,f,f,0,f,g,260,0,-
686,a,22.67,0.750,u,g,c,v,2.00,f,t,2,t,g,200,394,-
687,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1,t,g,200,1,-
688,b,17.92,0.205,u,g,aa,v,0.04,f,f,0,f,g,280,750,-
689,b,35,3.375,u,g,c,h,8.29,f,f,0,t,g,0,0,-

In [5]:
# remove ? in att2
crx = crx.drop(crx[crx["att2"]=="?"].index)
crx = crx.drop(crx[crx["att14"]=="?"].index)
crx = crx.reset_index(drop=True)
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15,label
0,b,30.83,0.000,u,g,w,v,1.25,t,t,1,f,g,202,0,+
1,a,58.67,4.460,u,g,q,h,3.04,t,t,6,f,g,43,560,+
2,a,24.5,0.500,u,g,q,h,1.50,t,f,0,f,g,280,824,+
3,b,27.83,1.540,u,g,w,v,3.75,t,t,5,t,g,100,3,+
4,b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,b,21.08,10.085,y,p,e,h,1.25,f,f,0,f,g,260,0,-
662,a,22.67,0.750,u,g,c,v,2.00,f,t,2,t,g,200,394,-
663,a,25.25,13.500,y,p,ff,ff,2.00,f,t,1,t,g,200,1,-
664,b,17.92,0.205,u,g,aa,v,0.04,f,f,0,f,g,280,750,-
665,b,35,3.375,u,g,c,h,8.29,f,f,0,t,g,0,0,-

In [6]:
crx["label"] = crx["label"].apply(lambda x:1 if x == "+" else -1)

In [7]:
for col in ["att1","att4","att5","att6","att7","att9","att10","att12","att13"]:
    crx[col] = le.fit_transform(crx[col])
crx_label = crx["label"]
crx = crx.drop("label",axis=1)
crx["att2"],crx["att14"] = pd.to_numeric(crx["att2"]),pd.to_numeric(crx["att14"])
crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15
0,2,30.83,0.000,1,0,13,8,1.25,1,1,1,0,0,202,0
1,1,58.67,4.460,1,0,11,4,3.04,1,1,6,0,0,43,560
2,1,24.50,0.500,1,0,11,4,1.50,1,0,0,0,0,280,824
3,2,27.83,1.540,1,0,13,8,3.75,1,1,5,1,0,100,3
4,2,20.17,5.625,1,0,13,8,1.71,1,0,0,0,2,120,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,2,21.08,10.085,2,2,5,4,1.25,0,0,0,0,0,260,0
662,1,22.67,0.750,1,0,2,8,2.00,0,1,2,1,0,200,394
663,1,25.25,13.500,2,2,6,3,2.00,0,1,1,1,0,200,1
664,2,17.92,0.205,1,0,1,8,0.04,0,0,0,0,0,280,750
665,2,35.00,3.375,1,0,2,4,8.29,0,0,0,1,0,0,0

In [40]:
# Normalization
def normalize(data):
    for i in data.columns:
        mean = data[i].mean()
        std = data[i].std()
        data[i] = (data[i] - mean)/std
    return data

In [43]:
norm_crx = normalize(crx)
norm_crx

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11,att12,att13,att14,att15
0,0.667039,-0.062000,-0.958598,-0.538994,-0.556124,1.453436,0.768080,-0.290453,0.943772,1.137807,-0.296049,-0.924050,-0.304250,0.115959,-0.191926
1,-1.290000,2.273536,-0.067544,-0.538994,-0.556124,0.989284,-0.814414,0.244259,0.943772,1.137807,0.718192,-0.924050,-0.304250,-0.811274,-0.084295
2,-1.290000,-0.593033,-0.858704,-0.538994,-0.556124,0.989284,-0.814414,-0.215772,0.943772,-0.877564,-0.498897,-0.924050,-0.304250,0.570828,-0.033555
3,0.667039,-0.313674,-0.650924,-0.538994,-0.556124,1.453436,0.768080,0.456351,0.943772,1.137807,0.515344,1.080567,-0.304250,-0.478870,-0.191349
4,0.667039,-0.956282,0.165209,-0.538994,-0.556124,1.453436,0.768080,-0.153041,0.943772,-0.877564,-0.498897,-0.924050,3.314147,-0.362237,-0.191926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,0.667039,-0.879941,1.056263,1.791979,1.802974,-0.403171,-0.814414,-0.290453,-1.057987,-0.877564,-0.498897,-0.924050,-0.304250,0.454195,-0.191926
662,-1.290000,-0.746554,-0.808757,-0.538994,-0.556124,-1.099398,0.768080,-0.066412,-1.057987,1.137807,-0.093201,1.080567,-0.304250,0.104296,-0.116200
663,-1.290000,-0.530114,1.738538,1.791979,1.802974,-0.171095,-1.210037,-0.066412,-1.057987,1.137807,-0.296049,1.080567,-0.304250,0.104296,-0.191733
664,0.667039,-1.145038,-0.917641,-0.538994,-0.556124,-1.331474,0.768080,-0.651906,-1.057987,-0.877564,-0.498897,-0.924050,-0.304250,0.570828,-0.047777
665,0.667039,0.287827,-0.284314,-0.538994,-0.556124,-1.099398,-0.814414,1.812547,-1.057987,-0.877564,-0.498897,1.080567,-0.304250,-1.062035,-0.191926

In [8]:
data

,ID,Diagnosis,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,Unnamed: 31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [9]:
data["Diagnosis"] = le.fit_transform(data["Diagnosis"])
data = data.drop("ID",axis=1)
data

,Diagnosis,3,4,5,6,7,8,9,10,11,...,23,24,25,26,27,28,29,30,31,Unnamed: 31
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [64]:
x_train,x_test,y_train,y_test = train_test_split(norm_crx,crx_label,test_size=0.25,random_state=1024)
# x_train,x_test,y_train,y_test = train_test_split(data.drop("Diagnosis",axis=1),data["Diagnosis"],test_size=0.25,random_state=1024)

# Q2:Linear classifier

In [65]:
# initialize weights
weights = np.random.randn(len(crx.columns))
constant = np.random.randn(1)
lr = 0.001
weights,constant

(array([-2.31408846,  0.27845664, -1.31022281,  1.30442089, -0.4115414 ,
         1.18063124,  0.99940232, -0.22107477, -2.05301077, -0.79743673,
        -1.85374199, -0.70496157, -0.83000669, -1.36424914, -0.13616502]),
 array([-1.4832475]))

In [66]:
# compute the value
for i in x_train.index:
    ind = np.random.choice(x_train.index)
    val = np.array(crx.iloc[ind,])
    pred = np.sign(np.dot(val,weights) + constant)
    if pred <= 0:
        weights = weights + lr * val * crx_label[ind]
        constant += crx_label[ind]
# weights

In [61]:
weights[np.where(weights < 0)] -= 1
weights

array([-1.56694271,  0.21505844,  0.81217719,  1.37836469,  1.40569835,
       -1.3145049 ,  1.12504551, -1.03636762,  1.55555991,  0.2604353 ,
        0.53700932,  0.52937896,  1.9535862 , -1.05404196, -1.12381057])

In [67]:
# testing
correct = 0
for i in range(len(x_test)):
    val = np.array(crx.iloc[i,])
    pred = np.sign(np.dot(val,weights) + constant)
    if pred == y_test.iloc[i,]:
        correct += 1
print("Linear Classifier Accuracy:{}".format(correct/len(y_test)))

Linear Classifier Accuracy:0.38323353293413176

# Q3:Least square method

In [14]:
# least square method
def least_square(x,y):
    constant = np.ones((len(x),1))
    x = np.concatenate((constant,np.matrix(x)),axis=1)
    y = y_train
    xTx = np.matmul(x.transpose(),x)
    xTx_inv = np.linalg.inv(xTx)
    xTy = np.matmul(x.transpose(),y)
    weights = np.matmul(xTx_inv,xTy)
    return weights

In [15]:
W = least_square(x_train,y_train)
W

matrix([[ 1.16187068e-01, -3.46620629e-02, -3.40749395e-03,
         -1.22570812e-03, -9.12803356e-01,  3.62003987e-01,
          1.65284761e-02,  3.95062460e-03,  2.73872856e-02,
          1.22921943e+00,  1.97081282e-01,  1.45974868e-02,
         -1.06843443e-01, -9.21116912e-04, -1.28609231e-04,
          1.14703971e-05]])

In [16]:
# testing
constant = np.ones((len(x_test),1))
x = np.concatenate((constant,np.matrix(x_test)),axis=1)
pred = np.sign((np.dot(x,W.transpose())))

In [17]:
correct = 0
for i in range(len(pred)):
    if pred[i] == y_test.iloc[i]:
        correct += 1
print("Least squared method Accuracy:{}".format(correct/len(pred)))

Least squared method Accuracy:0.8982035928143712

# Q4:Voted perceptron

In [18]:
all_weight = []
weights = np.random.randn(len(crx.columns))
constant = np.random.randn(1)
all_correct = []
correct = 0

In [19]:
for i in x_train.index:
    ind = np.random.choice(x_train.index)
    val = np.array(crx.iloc[ind,])
    pred = np.sign(np.dot(val,weights) + constant)
    if pred >= 0:
        correct += 1
    else:
        all_weight.append(weights)
        all_correct.append(correct)
        weights = weights + lr * val * crx_label[ind]
        constant += crx_label[ind]
        correct = 0

In [20]:
# testing
correct = 0
for i in x_test.index:
    val = np.array(crx.iloc[i,])
    positive,negative = 0,0
    for j in range(len(all_weight)):
        pred = np.sign(np.dot(val,all_weight[j]) + constant)
        if pred > 0:
            positive += pred * all_correct[j]
        else:
            negative += -pred * all_correct[j]
    if positive > negative:
        pred = 1
    else:
        pred = -1
    if pred == crx_label.iloc[i,]:
        correct += 1
print("Voted Perceptron Accuracy:{}".format(correct/len(y_test)))

Voted Perceptron Accuracy:0.38323353293413176

In [21]:
# Average voted perceptron
avg_vote = np.sum(all_weight,axis=0)/len(all_weight)
correct = 0
for i in x_test.index:
    val = np.array(crx.iloc[i,])
    pred = np.sign(np.dot(val,avg_vote) + constant)
    if pred == crx_label.iloc[i,]:
        correct += 1
print("Average voted perceptron Accuracy:{}".format(correct/len(y_test)))

Average voted perceptron Accuracy:0.38323353293413176

# Q5:Minimizing the ||w||^2

# Q6:Add slack variable based on Q5

# Q7:Use sklearn.svm

In [22]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [23]:
svm = SVC()

In [24]:
def svm_result(x_train,x_test,y_train,y_test):
    svm.fit(x_train,y_train)
    pred = svm.predict(x_test)
    print("SVM Accuracy score:{}".format(accuracy_score(y_test,pred)))

## For crx dataset

In [25]:
x_train,x_test,y_train,y_test = train_test_split(crx,crx_label,test_size=0.25,random_state=1024)

In [26]:
svm_result(x_train,x_test,y_train,y_test)

SVM Accuracy score:0.6946107784431138

## For data dataset

In [27]:
x_train,x_test,y_train,y_test = train_test_split(data.drop("Diagnosis",axis=1),data["Diagnosis"],test_size=0.25,random_state=1024)

In [28]:
svm_result(x_train,x_test,y_train,y_test)

SVM Accuracy score:0.9230769230769231